#pragma once

// From glfw3.h
#define ROOB_MOUSE_BUTTON_1         0
#define ROOB_MOUSE_BUTTON_2         1
#define ROOB_MOUSE_BUTTON_3         2
#define ROOB_MOUSE_BUTTON_4         3
#define ROOB_MOUSE_BUTTON_5         4
#define ROOB_MOUSE_BUTTON_6         5
#define ROOB_MOUSE_BUTTON_7         6
#define ROOB_MOUSE_BUTTON_8         7
#define ROOB_MOUSE_BUTTON_LAST      ROOB_MOUSE_BUTTON_8
#define ROOB_MOUSE_BUTTON_LEFT      ROOB_MOUSE_BUTTON_1
#define ROOB_MOUSE_BUTTON_RIGHT     ROOB_MOUSE_BUTTON_2
#define ROOB_MOUSE_BUTTON_MIDDLE    ROOB_MOUSE_BUTTON_3
